/**
 * Final run report — markdown, saved to .agents/report-<runId>.md.
 */
import path from "node:path";
import { BOARD_DIR } from "./blackboard.js";
import { formatMs, writeTextFile } from "./fsutil.js";
import { RunResult } from "./types.js";

export function renderReport(run: RunResult, runId: string): string {
  const lines: string[] = [];
  lines.push(`# PolyCoder Run Report — ${run.projectName}`);
  lines.push("");
  lines.push(`- **Run ID:** ${runId}`);
  lines.push(`- **Started:** ${run.startedAt}`);
  lines.push(`- **Duration:** ${formatMs(run.durationMs)}`);
  lines.push(`- **Mode:** ${run.mode}`);
  lines.push(`- **Status:** ${run.success ? "✅ success" : "❌ incomplete/failed"}`);
  lines.push(
    `- **Tokens:** ${run.totalUsage.inputTokens.toLocaleString()} in + ${run.totalUsage.outputTokens.toLocaleString()} out (${(run.totalUsage.inputTokens + run.totalUsage.outputTokens).toLocaleString()} total)`,
  );
  if (run.totalCostUsd > 0) lines.push(`- **Estimated cost:** $${run.totalCostUsd.toFixed(4)}`);
  lines.push("");
  lines.push(`## Task`);
  lines.push("");
  lines.push(run.task);
  lines.push("");

  lines.push(`## Role agents (${run.roles.length})`);
  lines.push("");
  lines.push(`| Role | Model | Provider | Files | Tokens (in+out) | Duration | Status |`);
  lines.push(`|---|---|---|---|---|---|---|`);
  for (const r of run.roles) {
    const tokens = (r.usage.inputTokens + r.usage.outputTokens).toLocaleString();
    lines.push(
      `| ${r.role.name} | ${r.model} | ${r.provider} | ${r.filesChanged.length} | ${tokens} | ${formatMs(r.durationMs)} | ${r.error ? `❌ ${r.error.slice(0, 80)}` : "✅"} |`,
    );
  }
  lines.push("");

  for (const r of run.roles) {
    lines.push(`### ${r.role.name} — ${r.role.description}`);
    lines.push("");
    lines.push(`- **Model:** ${r.model} via ${r.provider}`);
    lines.push(`- **Branch:** \`${r.branch}\``);
    if (r.filesChanged.length > 0) {
      lines.push(`- **Files changed:**`);
      for (const f of r.filesChanged) lines.push(`  - \`${f}\``);
    } else {
      lines.push(`- **Files changed:** none`);
    }
    if (r.notes.length > 0) {
      lines.push(`- **Notes for other agents:**`);
      for (const n of r.notes) lines.push(`  - ${n}`);
    }
    if (r.summary) {
      lines.push(`- **Summary:** ${r.summary}`);
    }
    if (r.error) lines.push(`- **Error:** ${r.error}`);
    lines.push("");
  }

  if (run.integrator) {
    const i = run.integrator;
    lines.push(`## Integrator`);
    lines.push("");
    lines.push(`- **Model:** ${i.model} via ${i.provider}`);
    lines.push(`- **Duration:** ${formatMs(i.durationMs)}`);
    lines.push(`- **Tokens:** ${(i.usage.inputTokens + i.usage.outputTokens).toLocaleString()}`);
    if (i.mergeConflictsResolved.length > 0) {
      lines.push(`- **Merge conflicts resolved:** ${i.mergeConflictsResolved.map((f) => `\`${f}\``).join(", ")}`);
    } else {
      lines.push(`- **Merge conflicts:** none`);
    }
    if (i.filesChanged.length > 0) {
      lines.push(`- **Files touched by integration:**`);
      for (const f of i.filesChanged) lines.push(`  - \`${f}\``);
    }
    if (i.summary) {
      lines.push("");
      lines.push(`**Integration summary:** ${i.summary}`);
    }
    if (i.error) lines.push(`\n**Error:** ${i.error}`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by PolyCoder — blackboard journals live in \`${BOARD_DIR}/status/\`._`);
  lines.push("");
  return lines.join("\n");
}

export async function writeReport(projectRoot: string, run: RunResult, runId: string): Promise<string> {
  const file = path.join(projectRoot, BOARD_DIR, `report-${runId}.md`);
  await writeTextFile(file, renderReport(run, runId));
  return file;
}
